newspaper/urls.py
from django.contrib import admin
from django.urls import path, include

from newspaper.views import (
    index,
    TopicListView,
    NewspaperListView,
    RedactorListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorDetailView,
    RedactorUpdateView,
    RedactorCreateView,
    RedactorDeleteView
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", index, name="index"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update"
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete"
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete"
    )
]

app_name = "newspaper"

newspaper_agency_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/", include("django.contrib.auth.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspaper/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from newspaper_agency_project import settings

from datetime import date


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.username})"

    def get_absolute_url(self):
        return reverse(
            "newspaper:redactor-detail", kwargs={"pk": self.pk}
        )


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateField(default=date.today)
    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
        related_name="newspapers"
    )
    publishers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="newspaper"
    )

    def __str__(self):
        return f"{self.title}"

newspaper/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from newspaper.models import Redactor, Newspaper


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "username",
            "first_name",
            "last_name",
            "email",
            "years_of_experience",
            "date_joined",
        )


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username"}
        )
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by title"}
        )
    )

newspaper/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from newspaper.forms import (
    RedactorCreationForm,
    TopicSearchForm,
    NewspaperSearchForm,
    RedactorSearchForm
)
from newspaper.models import Newspaper, Topic, Redactor


@login_required
def index(request: HttpRequest) -> HttpResponse:
    topics_count = Topic.objects.count()
    newspapers_count = Newspaper.objects.count()
    redactors_count = Redactor.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "topics_count": topics_count,
        "newspapers_count": newspapers_count,
        "redactors_count": redactors_count,
        "num_visits": num_visits + 1
    }

    return render(
        request,
        "newspaper/index.html",
        context=context
    )


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topic_list"
    template_name = "newspaper/topic_list.html"
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TopicSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Topic.objects.all()
        form = TopicSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")
    template_name = "newspaper/topic_form.html"


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")
    template_name = "newspaper/topic_form.html"


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")
    template_name = "newspaper/topic_confirm_delete.html"


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    queryset = Newspaper.objects.all().select_related("topic")
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = NewspaperSearchForm(
            initial={"title": title}
        )
        return context

    def get_queryset(self):
        queryset = Newspaper.objects.all()
        form = NewspaperSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                title__icontains=form.cleaned_data["title"]
            )
        return queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    fields = "__all__"
    success_url = reverse_lazy("newspaper:newspaper-list")
    template_name = "newspaper/newspaper_form.html"


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    fields = "__all__"
    success_url = reverse_lazy("newspaper:newspaper-list")
    template_name = "newspaper/newspaper_form.html"


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    fields = "__all__"
    success_url = reverse_lazy("newspaper:newspaper-list")
    template_name = "newspaper/newspaper_confirm_delete.html"


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = RedactorSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Redactor.objects.all()
        form = RedactorSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.prefetch_related("newspaper__topic")


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    success_url = reverse_lazy("newspaper:redactor-list")
    form_class = RedactorCreationForm


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    fields = [
        "username",
        "first_name",
        "last_name",
        "email",
        "years_of_experience",
        "date_joined"
    ]
    success_url = reverse_lazy("newspaper:redactor-list")
    template_name = "newspaper/redactor_form.html"


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    fields = "__all__"
    success_url = reverse_lazy("newspaper:redactor-list")
    template_name = "newspaper/redactor_confirm_delete.html"

templates/newspaper/index.html
{% extends 'layouts/base-presentation.html' %}

{% block title %} Presentation {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}

  <header class="header-2">
    <div class="page-header section-height-75 relative"
         style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/curved.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">
              <a class="text-white" target="_blank">Newspaper Agency</a>
            </h1>
            <hr style="color: white">
            <br>
            <p style="color: white">
              The Newspaper Agency serves as a centralized platform for
              accessing a diverse range of newspapers,
              offering users convenient access to current news and information
              from various sources.
              With a user-friendly interface and regular updates, the
              Newspaper Agency webpage caters to the needs of individuals
              seeking reliable and up-to-date news content.
            </p>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg"
             xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40"
             preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave"
                  d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1"
                 fill="rgba(255,255,255,0.40"/>
            <use xlink:href="#gentle-wave" x="48" y="3"
                 fill="rgba(255,255,255,0.35)"/>
            <use xlink:href="#gentle-wave" x="48" y="5"
                 fill="rgba(255,255,255,0.25)"/>
            <use xlink:href="#gentle-wave" x="48" y="8"
                 fill="rgba(255,255,255,0.20)"/>
            <use xlink:href="#gentle-wave" x="48" y="13"
                 fill="rgba(255,255,255,0.15)"/>
            <use xlink:href="#gentle-wave" x="48" y="16"
                 fill="rgba(255,255,255,0.95"/>
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div
            class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1"
                                                             countTo="{{ newspapers_count }}">0</span>
                </h1>
                <h5 class="mt-3">Newspapers</h5>
                <p class="text-sm">
                  Dive into a world of diverse perspectives with our extensive
                  collection of newspapers.
                </p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state2"
                                                             countTo="{{ redactors_count }}">0</span>
                </h1>
                <h5 class="mt-3">Publishers</h5>
                <p class="text-sm">
                  In an effort to provide reliable and relevant news content,
                  our platform is used by reputable publishers.
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary" id="state3"
                    countTo="{{ topics_count }}">0</h1>
                <h5 class="mt-3">Topics</h5>
                <p class="text-sm">
                  Explore the topics that matter most to you with ease.
                  Our carefully curated sections divide newspapers into
                  relevant categories.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <style>
      .visit-counter {
          text-align: center;
          font-size: 18px;
          color: #333; /* Adjust color as needed */
          font-family: Arial, sans-serif; /* Adjust font family as needed */
          margin-top: 50px; /* Adjust top margin for positioning */
      }
  </style>

  <div class="visit-counter">
    <p>You have visited this page {{ num_visits }}
      time{{ num_visits|pluralize }}.</p>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

  <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1"
          type="text/javascript"></script>
  <script type="text/javascript">
      if (document.getElementById('state1')) {
          const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
          if (!countUp.error) {
              countUp.start();
          } else {
              console.error(countUp.error);
          }
      }
      if (document.getElementById('state2')) {
          const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
          if (!countUp1.error) {
              countUp1.start();
          } else {
              console.error(countUp1.error);
          }
      }
      if (document.getElementById('state3')) {
          const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
          if (!countUp2.error) {
              countUp2.start();
          } else {
              console.error(countUp2.error);
          }
          ;
      }
  </script>

{% endblock javascripts %}

templates/newspaper/redactor_list.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %} Publishers {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} blog-author bg-gray-100 {% endblock body_class %}

{% block content %}

  {% include "includes/navigation-light.html" %}

  <link rel="stylesheet" type="text/css"
        href="{% static 'assets/css/styles.css' %}">

  <header class="bg-gradient-dark">
    <div class="page-header section-height-75"
         style="background-image: url('{{ ASSETS_ROOT }}/img/publisher.jpg')">
      <span class="mask bg-gradient-dark opacity-7"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">List of Publishers</h1>
            <p class="lead mb-4 text-white opacity-8">
              Experience quality journalism from renowned publishers across
              the globe.
              With a commitment to delivering reliable and up-to-date news
              content,
              our platform partners with respected publishers, providing you
              with
              access to credible sources you can trust. You can also become a
              publisher!
            </p>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg"
             xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40"
             preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave"
                  d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1"
                 fill="rgba(255,255,255,0.40"/>
            <use xlink:href="#gentle-wave" x="48" y="3"
                 fill="rgba(255,255,255,0.35)"/>
            <use xlink:href="#gentle-wave" x="48" y="5"
                 fill="rgba(255,255,255,0.25)"/>
            <use xlink:href="#gentle-wave" x="48" y="8"
                 fill="rgba(255,255,255,0.20)"/>
            <use xlink:href="#gentle-wave" x="48" y="13"
                 fill="rgba(255,255,255,0.15)"/>
            <use xlink:href="#gentle-wave" x="48" y="16"
                 fill="rgba(255,255,255,1"/>
          </g>
        </svg>
      </div>
    </div>
  </header>

  <section class="py-sm-5 py-5 position-relative">
    <a href="{% url "newspaper:redactor-create" %}">
      <button class="btn btn-outline-success"
              style="float: right; margin-right: 170px; font-size: 20px; padding: 10px 20px;">
        Create
      </button>
    </a>


    <div class="row">
      <div class="col-md-8 text-left mb-5 mt-5">

        <!-- Search Form -->
        <div class="form-group mt-3">
          <input type="text" id="searchInput" class="form-control"
                 placeholder="Search by username..."
                 style="width: 400px; margin-left: 29%"
                 oninput="searchRedactors()">
        </div>
        <!-- End of Search Form -->

      </div>
    </div>

    {% if redactor_list %}
      <div class="container">
        <div class="row" id="redactorList">
          {% for redactor in redactor_list %}
            {% if redactor == request.user %}
              <!-- Display the current user first in the list -->
              <div class="col-12 mx-auto">
                <div class="row py-lg-3 py-5">
                  <div
                      class="col-lg-7 col-md-4 z-index-2 position-relative px-md-5 px-sm-5 mt-sm-0 mt-4"
                      style="border: 1px solid #ccc; padding: 20px; margin: 20px;">
                    <div
                        class="d-flex justify-content-between align-items-center mb-2">

                      {% if not redactor.is_superuser %}
                        <div class="mb-4">
                          <h4 class="mb-0">
                            <a style="color: #66d432;border: 2px solid #66d432; padding: 3px; margin-left: 5px">Me</a>
                            <br>
                            <br>
                            <strong>First
                              name:</strong> {{ redactor.first_name }}
                            <br>
                            <strong>Last
                              name:</strong> {{ redactor.last_name }}
                          </h4>
                        </div>
                      {% else %}
                        <h5 class="mb-0"><strong>Username:</strong>
                          <em>{{ redactor.username }}</em>
                          <a style="color: #66d432; border: 2px solid #66d432; padding: 3px; margin-left: 5px">Me</a>
                          <br>
                        </h5><br>
                      {% endif %}

                      <div class="d-block">
                        <a href="{% url "newspaper:redactor-update" pk=redactor.id %}">
                          <button type="button" class="btn btn-info">
                            Update
                          </button>
                        </a>
                        <a href="{% url "newspaper:redactor-delete" pk=redactor.id %}">
                          <button type="button" class="btn btn-warning">
                            Delete
                          </button>
                        </a>
                      </div>
                    </div>

                    {% if not redactor.is_superuser %}
                      <div class="mb-4">
                        <h5 class="mb-0" style="color: #252f40">
                          <strong>Username: </strong>
                          <em>{{ redactor.username }}</em>
                        </h5>
                      </div>
                    {% endif %}

                  {% if redactor.is_superuser %}
                    <h5 class="mb-0"
                        style="color: red">
                      <strong>SUPERUSER</strong></h5>
                    <br>
                  {% endif %}

                    <p class="text-lg mb-0" style="color: black">Joining
                      date:</p>
                    <p class="text-lg mb-0">{{ redactor.date_joined }}</p>
                    <p>
                    <p style="color: #7928CA">ID: {{ redactor.id }}</p>
                    <a href="{% url "newspaper:redactor-detail" pk=redactor.id %}"
                       class="text-info icon-move-right">View details
                      <i class="fas fa-arrow-right text-sm ms-1"></i>
                    </a>
                  </div>
                </div>
              </div>
            {% endif %}

          {% endfor %}

          <!-- Display other users -->
          {% for redactor in redactor_list %}

            {% if redactor != request.user %}
              <div class="col-12 mx-auto">
                <div class="row py-lg-3 py-5">
                  <div
                      class="col-lg-7 col-md-4 z-index-2 position-relative px-md-5 px-sm-5 mt-sm-0 mt-4"
                      style="border: 1px solid #ccc; padding: 20px; margin: 20px">
                    <div
                        class="d-flex justify-content-between align-items-center mb-2">

                      {% if not redactor.is_superuser %}
                        <div class="mb-4">
                          <h4 class="mb-0">
                            <strong>First
                              name:</strong> {{ redactor.first_name }}
                            <br>
                            <strong>Last
                              name:</strong> {{ redactor.last_name }}
                          </h4>
                        </div>
                      {% else %}
                        <h5 class="mb-0"><strong>Username:</strong>
                          <em>{{ redactor.username }} </em>
                        </h5>
                        <br>
                      {% endif %}

                      <div class="d-block">
                        <a href="{% url "newspaper:redactor-update" pk=redactor.id %}">
                          <button type="button" class="btn btn-info">
                            Update
                          </button>
                        </a>
                        <a href="{% url "newspaper:redactor-delete" pk=redactor.id %}">
                          <button type="button" class="btn btn-warning">
                            Delete
                          </button>
                        </a>
                      </div>
                    </div>

                    {% if not redactor.is_superuser %}
                      <div class="mb-4">
                        <h5 class="mb-0" style="color: #252f40">
                          <strong>Username: </strong>
                          <em>{{ redactor.username }}</em>
                        </h5>
                      </div>
                    {% endif %}

                    {% if redactor.is_superuser %}
                      <h5 class="mb-0"
                          style="color: red">
                        <strong>SUPERUSER</strong></h5>
                      <br>
                    {% endif %}

                    <p class="text-lg mb-0" style="color: black">Joining
                      date:</p>
                    <p class="text-lg mb-0">{{ redactor.date_joined }}</p>
                    <p>
                    <p style="color: #7928CA">ID: {{ redactor.id }}</p>
                    <a href="{% url "newspaper:redactor-detail" pk=redactor.id %}"
                       class="text-info icon-move-right">View details
                      <i class="fas fa-arrow-right text-sm ms-1"></i>
                    </a>
                  </div>
                </div>
              </div>
            {% endif %}

          {% endfor %}

        </div>
      </div>
    {% else %}
      <h6 style="color: red">There are no publishers in the service!</h6>
    {% endif %}

    <!-- Pagination links -->
    {% if is_paginated %}
      <div class="pagination-wrapper">
        <div class="pagination">
          {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
              <li class="page-numbers current"><a class="page-link"
                                                  href="#">{{ num }}</a></li>
            {% else %}
              <li class="page-numbers"><a class="page-link"
                                          href="?page={{ num }}">{{ num }}</a>
              </li>
            {% endif %}
          {% endfor %}
        </div>
      </div>

      <div class="pagination-wrapper">
        {% if page_obj.has_previous %}
          <a class="prev page-numbers"
             href="?page={{ page_obj.previous_page_number }}">Prev</a>
        {% endif %}

        {% if page_obj.has_next %}
          <a class="next page-numbers"
             href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
      </div>

    {% else %}
    {% endif %}

  </section>

  <button onclick="goToTop()" id="btnGoToTop" title="Go to top">Go to top 👆
  </button>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }} /js/soft-design-system.min.js?v=1.0.1"
          type="text/javascript"></script>

  <script>
      function goToTop() {
          window.scrollTo({
              top: 0,
              behavior: "smooth"
          });
      }

      window.onscroll = function () {
          scrollFunction();
      };

      function scrollFunction() {
          if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
              document.getElementById("btnGoToTop").style.display = "block";
          } else {
              document.getElementById("btnGoToTop").style.display = "none";
          }
      }
  </script>

  <script>
      function searchRedactors() {
          var input, filter, redactors, redactor, i, txtValue;
          input = document.getElementById("searchInput");
          filter = input.value.toUpperCase();
          redactors = document.getElementById("redactorList").getElementsByClassName("row");
          for (i = 0; i < redactors.length; i++) {
              redactor = redactors[i].getElementsByTagName("em")[0];
              if (redactor) {
                  txtValue = redactor.textContent || redactor.innerText;
                  if (txtValue.toUpperCase().indexOf(filter) > -1) {
                      redactors[i].style.display = "";
                  } else {
                      redactors[i].style.display = "none";
                  }
              }
          }
      }
  </script>

{% endblock javascripts %}